/*
 * SaaS Physics v2 — CUSTOMER PHYSICS (Gate A). Pure transition functions.
 *
 * With Customer Physics on, a cohort's dollar retention is no longer an
 * asserted persistence coefficient: it is GENERATED by customer mechanics.
 *
 *   l  = logoRetentionAnnual ^ (1/12)            monthly logo survival
 *   cM = 1 − (1 − contractionAnnual) ^ (1/12)     monthly contraction among survivors
 *   e  = (1 + expansionCoefficientAnnual)^(1/12) − 1   monthly expansion among survivors
 *
 *   customers:   n1 = n0 × l
 *   logo churn:  departing customers take the cohort's average revenue  → openingMRR × (1 − l)
 *   survivors:   openingMRR × l
 *   contraction: survivors × cM                                          (customer survives, spends less)
 *   retained:    survivors − contraction = openingMRR × l × (1 − cM)
 *   expansion:   retained × e                                            (customer survives, spends more)
 *   closing:     retained + expansion
 *
 * so leakage = logo churn + contraction = openingMRR × (1 − l(1 − cM)) and the
 * v1.3 identity closing = opening × g × (1 + e) holds with g = l(1 − cM):
 * persistence is DERIVED, P = L(1 − C), never an input while this layer is on.
 * Two worlds with the same l(1 − cM)(1 + e) have the same ARR path and the
 * same NRR — and different customers, logo retention and ARPA. That is the
 * layer's signature.
 *
 * Customers are a continuous cohort count, deliberately not integers: this
 * is an aggregate cohort model, not a simulation of individual accounts.
 *
 * This module keeps no state and knows nothing about acquisition, cash or
 * the company. The engine passes a cohort's opening state in and takes the
 * transition out.
 */
;(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.SaaSPhysicsCustomers = factory();
})(typeof self !== 'undefined' ? self : globalThis, function () {
  'use strict';

  function enabled(a) {
    var L = a.logoRetentionAnnual;
    return L !== null && L !== undefined;
  }

  function validate(a) {
    var L = a.logoRetentionAnnual, C = a.contractionAnnual, K = a.newLogoARPA;
    if (L === undefined) a.logoRetentionAnnual = null;
    else if (L !== null && (typeof L !== 'number' || !(L > 0) || L > 1))
      throw new RangeError('logoRetentionAnnual must be null (Customer Physics off) or a number in (0, 1] (got ' + String(L) + ')');
    if (C === undefined) a.contractionAnnual = 0;
    else if (typeof C !== 'number' || !(C >= 0) || C >= 1)
      throw new RangeError('contractionAnnual must be a number in [0, 1) (got ' + String(C) + ')');
    if (K === undefined) a.newLogoARPA = null;
    else if (K !== null && (typeof K !== 'number' || !(K > 0)))
      throw new RangeError('newLogoARPA must be null (use the opening ARPA) or a number > 0 (got ' + String(K) + ')');
    if (enabled(a) && a.bands && a.bands.length)
      throw new RangeError('Customer Physics uses flat customer laws; age bands cannot be combined with logoRetentionAnnual (Gate A boundary)');
    return a;
  }

  function rates(law) {
    var L = law.logoRetentionAnnual, C = law.contractionAnnual || 0, X = law.expansionCoefficientAnnual;
    var l = Math.pow(L, 1 / 12), cM = 1 - Math.pow(1 - C, 1 / 12), e = Math.pow(1 + X, 1 / 12) - 1;
    return { l: l, cM: cM, e: e, g: l * (1 - cM), impliedPersistenceAnnual: L * (1 - C) };
  }

  /* One cohort, one month. opening = { n, mrr }. */
  function transition(opening, r) {
    var n1 = opening.n * r.l;
    var logoChurnMRR = opening.mrr * (1 - r.l);
    var survMRR = opening.mrr * r.l;
    var contractionMRR = survMRR * r.cM;
    var retainedMRR = survMRR - contractionMRR;
    var expansionMRR = retainedMRR * r.e;
    return {
      customersOpening: opening.n, customersClosing: n1, logoChurnCustomers: opening.n - n1,
      logoChurnMRR: logoChurnMRR, survivorMRR: survMRR, contractionMRR: contractionMRR,
      retainedMRR: retainedMRR, leakageMRR: logoChurnMRR + contractionMRR,
      expansionMRR: expansionMRR, closingMRR: retainedMRR + expansionMRR
    };
  }

  return { enabled: enabled, validate: validate, rates: rates, transition: transition };
});
