/*
 * SaaS Physics — Prototype 0
 * Deterministic monthly economic engine. No DOM, no randomness, no I/O.
 *
 * ONE source of truth: this file is required by the Node checks/scenarios AND
 * inlined verbatim into the inspection UI by build.js. Base and Experiment
 * scenarios call the same run() with different assumption objects.
 *
 * LAYER A — ECONOMIC / STATE-TRANSITION ENGINE.
 * This file is the world, not the report on it. Its parameters are TRANSITION
 * COEFFICIENTS that govern how cohort ARR state evolves month to month. They are
 * deliberately NOT the CFO-reported KPIs of the same-sounding names: the reported
 * KPIs are computed by Layer B (kpi.js) by measuring this world's output. See
 * docs/MEASUREMENT.md.
 *
 * RECURRING-REVENUE STATE (v0.3 clarity-pass follow-up, MRR-native refactor).
 * The cohort/company recurring-revenue state the engine actually carries and
 * evolves month to month is MRR (openingMRR/retainedMRR/leakageMRR/
 * expansionMRR/closingMRR/newMRR, and Revenue = (OpeningMRR+ClosingMRR)/2 —
 * no /12 anywhere in the transition). ARR (openingARR/closingARR/leakage/
 * expansion/newARR, all pre-existing field names) is kept as a DERIVED
 * reporting view, computed as exactly 12 x the matching MRR quantity in the
 * same month — never re-derived independently. This is a unit refactor: the
 * transition coefficients, their order of application, the KPI definitions
 * and every scenario are unchanged; only which unit is native moved from ARR
 * to MRR. See docs/ARCHITECTURE.md.
 *
 * MODEL VERSION: v2.0  (the Economic System layers on top of the frozen v1.3 ARR physics)
 *   v1.3 → v2 Gate A  CUSTOMER PHYSICS (customers.js). A cohort carries a
 *     customer count; its dollar transition is generated by logo survival,
 *     contraction among survivors and expansion among survivors, so
 *     persistence is DERIVED, P = L(1 − C), and persistenceAnnual is not read
 *     while the layer is on. Null: logoRetentionAnnual null — the v1.3 world,
 *     every field (v2-checks.js ALL-NULL-V13 vs baseline-v1.3-full.json.gz).
 *   The v1.x mechanisms, unchanged:
 *   v1.0 → v1.1  EXPANSION ECONOMICS. One economic input, expansionCostPerARR:
 *     the cost of realising €1 of expansion ARR. A cost line only — it reaches
 *     EBITA/FCF/cash and touches no ARR state. Null: 0.
 *   v1.1 → v1.2  BOUNDED ACQUISITION. One constraint, maxMonthlyNewARR: a
 *     saturating acquisition response with cacPerARR kept as the low-spend
 *     primitive. Null: disabled (null / non-finite) — the linear law.
 *   v1.2 → v1.3  ACQUISITION TIMING. One timing parameter, acquisitionLagMonths:
 *     S&M spent at t creates a pending acquisition that becomes a cohort at
 *     t + L. Explicit engine state, not a chart shift. Null: 0.
 *   Each mechanism is nullable on its own; with all three at null the v1.0
 *   world is reproduced (physics-checks.js, ALL-NULL, against baseline-v1.0.json).
 *   v0.2.1 → v0.3: ONE new state dimension — cohort maturity. Transition
 *   coefficients may vary by cohort age band. Defaults are FLAT (all bands
 *   identical), so the shipped default reproduces v0.2.1 exactly and the model
 *   privileges no direction. Cohorts also carry acquisition-cost provenance.
 *   v0.1 → v0.2: the acquisition primitive is inverted. CAC per €1 of New ARR is
 *   now the input and CAC payback is an emergent output. Everything else about the
 *   engine is unchanged. Weaknesses are flagged in docs/FINDINGS.md, never silently
 *   "improved".
 */
;(function (root, factory) {
  /* v2: the layer modules are pure transition functions in their own files.
     Node resolves them with require; the built HTML inlines them BEFORE this
     file (build.js), so the browser finds them on the global. */
  var isNode = typeof module === 'object' && module.exports;
  var deps = isNode
    ? { customers: require('./customers.js'), monetization: require('./monetization.js') }
    : { customers: root.SaaSPhysicsCustomers, monetization: root.SaaSPhysicsMonetization };
  if (isNode) module.exports = factory(deps);
  else root.SaaSPhysics = factory(deps);
})(typeof self !== 'undefined' ? self : globalThis, function (deps) {
  'use strict';

  var CU = deps.customers;               /* Gate A — Customer Physics */
  var MO = deps.monetization;            /* Gate B — Monetization Physics */
  var HORIZON = 60;

  /* ------------------------------------------------------------------ *
   * 15. Conceptual classification — kept explicit, not collapsed to KPIs
   * ------------------------------------------------------------------ */
  var TAXONOMY = {
    STATE: {
      openingARR:  'Installed-base ARR at start of month (stock)',
      closingARR:  'Installed-base ARR at end of month (stock)',
      cohortARR:   'Per-cohort ARR balance (stock)',
      cash:        'Cash balance (stock)',
      pendingAcquisition: 'v1.3 — S&M already spent whose New ARR has not yet matured into a cohort (stock, in € of ARR and € of spend)'
    },
    FLOW: {
      newARR:      'ARR added by acquisition this month (v1.3: realised this month, which under a lag is the spend of month t − L)',
      expansion:   'ARR added by the installed base this month',
      leakage:     'ARR lost by the installed base this month (churn + contraction combined in v0.1)',
      revenue:     'Recognised revenue this month',
      cogs:        'Cost of revenue this month',
      grossProfit: 'Revenue less COGS this month',
      expansionCost: 'v1.1 — cost of realising this month\'s expansion ARR = expansion ARR × expansionCostPerARR. An economic realisation cost line; not classified as COGS, S&M or CSM.',
      ebita:       'Gross profit less S&M, R&D, G&A and expansion realisation cost',
      fcf:         'Free cash flow (= EBITA in v0.1)'
    },
    /* TRANSITION COEFFICIENTS — they govern the world. They are not measurements,
       and they do not equal the KPIs of similar name. */
    TRANSITION: {
      persistenceAnnual:          'Annual persistence coefficient — 12-month multiplicative survival of installed ARR, applied BEFORE expansion. NOT reported GRR.',
      expansionCoefficientAnnual: 'Annual expansion coefficient — 12-month compounded expansion factor applied to RETAINED ARR. NOT reported expansion.',
      grossMargin:                'Gross margin coefficient',
      cacPerARR:                  'Acquisition spend per €1 of New ARR at low spend — dimensionless acquisition productivity (v1.2: the low-spend limit of the saturating response)',
      expansionCostPerARR:        'v1.1 — € of realisation cost per €1 of expansion ARR. Reaches economics only; never the ARR transition. 0 = free expansion (the v1.0 world).',
      maxMonthlyNewARR:           'v1.2 — acquisition capacity: the New ARR per month the response approaches as S&M → ∞. null = no bound (the v1.0 linear law). A BOUND on an optimistic mechanism, never a benefit.',
      acquisitionLagMonths:       'v1.3 — months between S&M spend and the cohort it creates. Changes WHEN ARR appears, never how much per euro. 0 = same-month (the v1.0 world).'
    },
    CONTROL: {
      sm: 'Monthly S&M investment (management control)',
      rd: 'Monthly R&D investment (management control)',
      ga: 'Monthly G&A investment (management control)'
    },
    /* MEASURED — produced by Layer B (kpi.js) by observing the world. Never settable. */
    MEASURED: {
      r12mGRR:          'R12M gross revenue retention over a frozen eligible cohort — see kpi.js',
      r12mExpansion:    'R12M expansion rate over the same frozen cohort',
      r12mNRR:          'R12M net revenue retention = closing eligible ARR / opening ARR',
      cacPaybackMonths: 'Months of gross profit to repay acquisition cost — OUTPUT of cacPerARR and gross margin',
      arrGrowthYoY:     'ARR growth',
      ebitaMargin:      'EBITA margin',
      burn:             'Cash burn when FCF < 0'
    }
  };

  /* Illustrative defaults. Not real company data. */
  var DEFAULT_ASSUMPTIONS = {
    sm:                         900000,  // CONTROL   €/month
    cacPerARR:                  1.20,    // TRANSITION € of S&M per €1 of New ARR
    persistenceAnnual:          0.90,    // TRANSITION 12-month survival factor of installed ARR, before expansion
    expansionCoefficientAnnual: 0.10,    // TRANSITION 12-month compounded expansion factor applied to RETAINED ARR
    grossMargin:                0.80,    // TRANSITION
    rd:                         700000,  // CONTROL   €/month
    ga:                         350000,  // CONTROL   €/month
    /* v1.1–v1.3 — each at its NULL setting, so the default world is v1.0 exactly */
    expansionCostPerARR:        0,       // v1.1  € of cost per €1 of expansion ARR; 0 = free (v1.0)
    maxMonthlyNewARR:           null,    // v1.2  € of New ARR per month the response saturates toward; null = unbounded (v1.0)
    acquisitionLagMonths:       0,       // v1.3  months from S&M spend to cohort creation; 0 = same month (v1.0)
    /* v2 Gate A — CUSTOMER PHYSICS, at its NULL setting (the v1.3 world). With
       logoRetentionAnnual set, persistenceAnnual is NOT READ: dollar persistence
       is generated as L(1 − C) by customers.js. */
    logoRetentionAnnual:        null,    // A   12-month logo (customer) survival; null = Customer Physics off
    contractionAnnual:          0,       // A   12-month revenue contraction among surviving customers
    newLogoARPA:                null,    // A   € ARR per newly acquired customer; null = the opening ARPA
    /* v2 Gate B — MONETIZATION PHYSICS, at its NULL setting (the Gate A world).
       { components: [{ name, kind: 'fixed'|'variable', penetration, units,
       priceAnnual, priceGrowthAnnual, usageGrowthAnnual, unitsCap,
       adoptionAnnual, penetrationCap }] }. Requires Customer Physics. When
       on: expansionCoefficientAnnual, newLogoARPA and start.openingARR are
       NOT READ — revenue is derived from per-customer components. */
    monetization:               null     // B   null = revenue is a carried balance (v1.3 / Gate A)
  };
  /* AGE BANDS (v0.3). Three bands by cohort age in months at the START of a month:
     band 1 covers ages 0..11, band 2 covers 12..23, band 3 covers 24 and above.
     Each band carries its OWN persistence and expansion coefficient — six
     transition parameters in total, and no other new behavioural coefficient.

     The DEFAULT is flat: every band inherits the scalar coefficients, so the
     default world is exactly v0.2.1 and age carries no economic meaning until a
     user makes it carry some. The simulator takes no position on whether older
     cohorts are better, worse, or the same. */
  var BAND_EDGES = [12, 24, Infinity];
  var BAND_NAMES = ['Early', 'Developing', 'Mature'];

  function resolveBands(a) {
    if (a.bands && a.bands.length === 3) return a.bands;
    return BAND_NAMES.map(function (n, i) {
      return { name: n, maxAgeExclusive: BAND_EDGES[i],
               persistenceAnnual: a.persistenceAnnual,
               expansionCoefficientAnnual: a.expansionCoefficientAnnual };
    });
  }
  function bandFor(bands, ageAtStart) {
    for (var i = 0; i < bands.length; i++) if (ageAtStart < bands[i].maxAgeExclusive) return i;
    return bands.length - 1;
  }

  /* NOTE ON NAMES. persistenceAnnual is NOT reported GRR and expansionCoefficientAnnual
     is NOT reported expansion. At these defaults the measurement layer reports GRR
     89.56% and expansion 9.44% — see rateDiagnostics() and docs/MEASUREMENT.md. */
  /* cacPerARR 1.20 with GM 80% reproduces the v0.1 baseline exactly:
     v0.1 CAC payback 18 months  ⇔  cacPerARR = payback × GM / 12 = 18 × 0.80 / 12 = 1.20 */

  var DEFAULT_START = {
    openingARR:  20000000,      // STATE €20.0m
    openingCash: 10000000,      // STATE €10.0m
    /* v0.3: the opening base may be a portfolio of vintages. Each entry is
       { arr, age } where age is the cohort's age in months at t=0. Omit for the
       v0.2.1 behaviour of one opening cohort at age 0. */
    openingCohorts: null,
    /* v2 Gate A: the opening base's customer count. Illustrative, like
       openingARR (→ opening ARPA €20k). Read ONLY when Customer Physics is on;
       an opening vintage carries its own { customers } when the layer is on. */
    openingCustomers: 1000
  };

  /* ------------------------------------------------------------------ *
   * Rate conversions (spec §5)
   * ------------------------------------------------------------------ */
  function toMonthlyPersistence(persistenceAnnual) { return Math.pow(persistenceAnnual, 1 / 12); }

  /* Geometric conversion so that 12 compounded monthly steps reproduce the
   * stated annual expansion exactly: (1+e_m)^12 = 1+e_a */
  function toMonthlyExpansion(expAnnual) { return Math.pow(1 + expAnnual, 1 / 12) - 1; }

  /* ------------------------------------------------------------------ *
   * v0.2 acquisition physics
   *
   * PRIMITIVE — acquisition productivity, a dimensionless ratio:
   *   cacPerARR = acquisition spend / New ARR generated
   *
   * New ARR generated per year of spend:
   *   annual New ARR = (Monthly S&M x 12) / cacPerARR
   * so the ARR added to the stock in one month is:
   *   monthly New ARR = Monthly S&M / cacPerARR
   *
   * UNITS. sm is €/month. cacPerARR is dimensionless. newARRPerMonth is therefore
   * € of ARR (an annualised-run-rate quantity) added to the ARR stock each month —
   * the same interpretation the v0.1 engine used, so every downstream identity,
   * cohort rule and reconciliation is untouched.
   *
   * Gross margin does NOT appear here. That is the whole point of v0.2: acquisition
   * productivity determines how much ARR the spend creates; gross margin determines
   * how fast that investment is recovered, and shows up in cacPaybackMonths below.
   *
   * Still linear, instantaneous and unbounded in S&M — no capacity, ramp, pipeline,
   * conversion, diminishing returns or acquisition lag. See FINDINGS.md.
   * ------------------------------------------------------------------ */
  /* ------------------------------------------------------------------ *
   * v1.2 BOUNDED ACQUISITION — a saturating response, one parameter.
   *
   *   N(sm) = sm / (cacPerARR + sm / maxMonthlyNewARR)
   *
   *   sm → 0    N ≈ sm / cacPerARR           (the v1.0 linear law, exactly in the limit)
   *   sm → ∞    N → maxMonthlyNewARR         (acquisition capacity)
   *
   * cacPerARR keeps its meaning as the LOW-SPEND acquisition-efficiency
   * primitive. The bound is switched OFF when maxMonthlyNewARR is null,
   * undefined or non-finite: then N = sm / cacPerARR, with no Infinity
   * arithmetic anywhere. A finite capacity ≤ 0 means no acquisition capacity
   * at all and yields N = 0 (the limit of the law as capacity → 0+); the
   * product never produces it, and it is not silently clamped to "off".
   *
   * Derived from the same law, analytically (no finite differences):
   *   average CAC   = sm / N            = cacPerARR + sm / cap
   *   dN/dsm        = cacPerARR / (cacPerARR + sm / cap)²
   *   marginal CAC  = 1 / (dN/dsm)      = (cacPerARR + sm / cap)² / cacPerARR
   *   utilisation   = N / cap
   * With the bound off: average CAC = marginal CAC = cacPerARR.
   *
   * This is a BOUND on an optimistic mechanism (FINDINGS #10), not a growth
   * benefit. The model exposes the curve; it declares no optimum and no
   * stopping rule — those need an objective function it does not have.
   * ------------------------------------------------------------------ */
  function saturationEnabled(a) {
    var cap = a.maxMonthlyNewARR;
    return cap !== null && cap !== undefined && isFinite(cap);
  }
  function newARRPerMonth(a) {
    if (!(a.cacPerARR > 0)) return 0;
    if (!saturationEnabled(a)) return a.sm / a.cacPerARR;
    var cap = a.maxMonthlyNewARR;
    if (!(cap > 0)) return 0;
    return a.sm / (a.cacPerARR + a.sm / cap);
  }
  /* The acquisition response and its derivatives at the run's own S&M, or at
     any S&M passed in. Pure function of the assumptions — the same law run()
     uses, differentiated by hand. */
  function acquisitionResponse(a, smOverride) {
    a = normaliseAssumptions(a);
    var sm = smOverride === undefined ? a.sm : smOverride;
    var probe = Object.assign({}, a, { sm: sm });
    var N = newARRPerMonth(probe);
    var enabled = saturationEnabled(a), cap = a.maxMonthlyNewARR;
    var dN, avgCAC, margCAC;
    if (!(a.cacPerARR > 0) || (enabled && !(cap > 0))) {
      dN = 0; avgCAC = Infinity; margCAC = Infinity;
    } else if (!enabled) {
      dN = 1 / a.cacPerARR; avgCAC = a.cacPerARR; margCAC = a.cacPerARR;
    } else {
      var denom = a.cacPerARR + sm / cap;
      dN = a.cacPerARR / (denom * denom);
      avgCAC = denom;                       // = sm / N, exactly, for sm > 0
      margCAC = (denom * denom) / a.cacPerARR;
    }
    var gm = a.grossMargin > 0 ? a.grossMargin : 0;
    return {
      sm: sm, newARR: N, enabled: enabled, capacity: enabled ? cap : null,
      dNewARRdSM: dN,
      averageCAC: avgCAC,
      marginalCAC: margCAC,
      averagePaybackMonths: gm > 0 && isFinite(avgCAC) ? avgCAC * 12 / gm : Infinity,
      marginalPaybackMonths: gm > 0 && isFinite(margCAC) ? margCAC * 12 / gm : Infinity,
      utilisation: enabled && cap > 0 ? N / cap : null
    };
  }

  /* MRR-NATIVE. cacPerARR is unchanged as the public assumption — € of S&M
   * per €1 of annualised New ARR, still 1.20 by default. The engine's own
   * state is MRR, so New MRR is simply New ARR ÷ 12 — the same acquisition
   * formula above, taken in the unit the engine now carries forward.
   * Normalised the other way round, this is S&M ÷ cacPerMRR with
   * cacPerMRR = cacPerARR x 12 = 14.40 by default; both give the same
   * number, exactly. */
  function cacPerMRR(a) { return a.cacPerARR * 12; }
  function newMRRPerMonth(a) { return newARRPerMonth(a) / 12; }

  /* EMERGENT. Months of gross profit needed to repay the acquisition cost of €1 of
   * New ARR:  CAC = cacPerARR;  monthly gross profit on €1 of ARR = GM / 12.
   *   payback = cacPerARR / (GM / 12) = cacPerARR x 12 / GM
   * Equivalently, in MRR terms: CAC = cacPerMRR; monthly gross profit on €1
   * of MRR = GM (MRR already IS the monthly amount) — payback = cacPerMRR / GM,
   * the same number.
   * Never an input, and never used to generate New ARR/MRR. */
  function cacPaybackMonths(a) {
    if (!(a.grossMargin > 0)) return Infinity;
    return (a.cacPerARR * 12) / a.grossMargin;
  }

  /* ------------------------------------------------------------------ *
   * Assumption normalisation and validation — the engine boundary.
   *
   * The engine never silently reinterprets an invalid economic input. A lag
   * that is negative, fractional, NaN, non-numeric or infinite is REJECTED
   * (RangeError) rather than clamped or rounded: a silently-coerced lag
   * would reshape the cash path, and a NaN lag would date every pending
   * entry to never mature — all acquisition lost with S&M still spent.
   * `undefined` means "not provided" and takes the default, as Object.assign
   * would otherwise copy it over the default.
   *
   * Capacity is canonicalised: null / undefined / ±Infinity all mean "no
   * bound" and are stored as null, so two runs with the bound off compare
   * equal whichever spelling the caller used. A finite capacity < 0 or NaN is
   * rejected; 0 is kept (no acquisition capacity, N = 0 — documented).
   * ------------------------------------------------------------------ */
  function validateAssumptions(a) {
    var L = a.acquisitionLagMonths;
    if (L === undefined) a.acquisitionLagMonths = DEFAULT_ASSUMPTIONS.acquisitionLagMonths;
    else if (typeof L !== 'number' || !isFinite(L) || L < 0 || Math.floor(L) !== L)
      throw new RangeError('acquisitionLagMonths must be an integer >= 0 (got ' + String(L) + ')');
    var cap = a.maxMonthlyNewARR;
    if (cap === undefined || cap === null || cap === Infinity || cap === -Infinity) a.maxMonthlyNewARR = null;
    else if (typeof cap !== 'number' || isNaN(cap) || cap < 0)
      throw new RangeError('maxMonthlyNewARR must be null (no bound) or a finite number >= 0 (got ' + String(cap) + ')');
    CU.validate(a);                                  /* v2 Gate A boundary */
    MO.validate(a, CU.enabled(a));                   /* v2 Gate B boundary (requires Gate A) */
    return a;
  }
  function normaliseAssumptions(a) {
    return validateAssumptions(Object.assign({}, DEFAULT_ASSUMPTIONS, a || {}));
  }

  /* ------------------------------------------------------------------ *
   * v1.3 PENDING ACQUISITION — the two state transitions, as pure functions.
   *
   * pendingEntry(a, t, L, newARR): S&M spent at t under the acquisition law in
   * force at t. The entry records WHAT the law was (coefficient, capacity or
   * null) and WHAT it produced, so the provenance of committed spend is fixed
   * at commitment. Later assumptions cannot rewrite it: nothing downstream
   * ever re-derives these fields from a live assumption object.
   *
   * realiseCohort(t, matured, bandName, grossMargin): the matured entries
   * become the month-t cohort. The signature deliberately takes NO assumption
   * object — every provenance stamp is read from the entries, and the only
   * live inputs are the band name and the gross margin the birth-month
   * revenue needs. That is what makes "stamped from the pending entry, not
   * the live law" a structural fact rather than a convention, and what lets
   * the integrity suite prove it by calling this function with a synthetic
   * entry whose law differs from any assumption the engine holds.
   * ------------------------------------------------------------------ */
  function pendingEntry(a, t, L, newARR, newLogoARPA, perCustomerState) {
    return {
      spendMonth: t, matureMonth: t + L, lagMonths: L,
      sm: a.sm, newARR: newARR,
      cacPerARRAtSpend: a.cacPerARR,
      maxMonthlyNewARRAtSpend: saturationEnabled(a) ? a.maxMonthlyNewARR : null,   // null = bound off at spend
      /* v2 Gate A: € ARR per new logo in force at spend; null = Customer Physics off.
         The cohort's customer count is realised FROM THIS, never from a live value. */
      newLogoARPAAtSpend: (newLogoARPA === undefined || newLogoARPA === null) ? null : newLogoARPA,
      /* v2 Gate B: the per-customer component state new logos start with, in
         force at spend; null = Monetization off. The cohort is born from it. */
      perCustomerAtSpend: perCustomerState ? MO.copyState(perCustomerState) : null,
      realised: false, cohortId: null
    };
  }
  function realiseCohort(t, matured, bandName, grossMargin) {
    var realisedARR = 0, realisedSpend = 0, first = matured[0];
    var realisedCustomers = 0, anyCustomers = false;
    for (var i = 0; i < matured.length; i++) {
      var e = matured[i];
      e.realised = true; e.cohortId = 'M' + t;
      realisedARR += e.newARR; realisedSpend += e.sm;
      if (e.spendMonth < first.spendMonth) first = e;
      /* v2 Gate A: customers = ARR ÷ ARR per new logo, entry by entry, from the
         value stamped at spend. Null on every entry = Customer Physics off. */
      if (e.newLogoARPAAtSpend !== null && e.newLogoARPAAtSpend !== undefined) {
        anyCustomers = true; realisedCustomers += e.newARR / e.newLogoARPAAtSpend;
      }
    }
    var realisedMRR = realisedARR / 12;
    var nc = {
      id: 'M' + t, label: 'M' + t, acquisitionMonth: t, initialAge: 0,
      initialARR: realisedARR, live: realisedMRR, rows: [],
      /* PROVENANCE (§2). Stamped once, at creation, FROM THE PENDING ENTRY —
         the acquisition economics in force when the spend was incurred.
         Immutable thereafter, and never read by any forward transition — a
         sunk cost, not a forward penalty. cacPerARRAtCreation is the REALISED
         cost per €1 of ARR (= acquisitionCost / initialARR), which equals the
         coefficient only while the bound was off at spend; the coefficient
         and the capacity at spend are stamped separately. */
      acquisitionCost: realisedSpend,
      cacPerARRAtCreation: realisedARR > 0 ? realisedSpend / realisedARR : null,
      cacCoefficientAtCreation: first.cacPerARRAtSpend,
      capacityAtSpend: first.maxMonthlyNewARRAtSpend,
      spendMonth: first.spendMonth,
      lagMonths: t - first.spendMonth,
      sourceEntries: matured.length,
      /* v2 Gate A — customer state. null = Customer Physics off. */
      initialCustomers: anyCustomers ? realisedCustomers : null,
      customers: anyCustomers ? realisedCustomers : null,
      /* v2 Gate B — per-customer component state, from the first entry */
      money: first.perCustomerAtSpend ? MO.copyState(first.perCustomerAtSpend) : null
    };
    if (nc.money) {
      /* every matured entry must carry the same per-customer state: a cohort
         has one ARPA. Entries priced differently maturing together is a
         boundary, not something to average away. */
      for (var j = 0; j < matured.length; j++)
        if (JSON.stringify(matured[j].perCustomerAtSpend) !== JSON.stringify(first.perCustomerAtSpend))
          throw new RangeError('pending entries with different per-customer monetization states matured in the same month (M' + t + ')');
    }
    var ncRevenue = (0 + realisedMRR) / 2;    // half a month of MRR, same midpoint rule
    nc.rows.push({
      t: t, age: 0, ageAtStart: -1, band: 0, bandName: bandName,
      openingMRR: 0, retainedMRR: 0, leakageMRR: 0, expansionMRR: 0, closingMRR: realisedMRR,
      openingARR: 0, retainedARR: 0, leakage: 0, expansion: 0, closingARR: realisedARR,
      revenue: ncRevenue, grossProfit: ncRevenue * grossMargin, expansionCost: 0,
      customers: anyCustomers ? customerRow(0, realisedCustomers, 0, 0, 0, realisedCustomers) : null,
      monetization: nc.money ? monetizationRow(realisedCustomers, nc.money, nc.money, moRatesFor(nc.money), null) : null
    });
    return nc;
  }

  /* v2 Gate A — the customer sub-record of a cohort row. Flows are in MRR
     (the engine's unit) with ARR readouts, like every other row field. */
  function customerRow(nOpen, nClose, logoChurnMRR, contractionMRR, survivorMRR, newCustomers) {
    var nNew = newCustomers || 0;
    return {
      opening: nOpen, closing: nClose, newCustomers: nNew, logoChurn: nOpen + nNew - nClose,
      logoChurnMRR: logoChurnMRR, contractionMRR: contractionMRR, survivorMRR: survivorMRR,
      logoChurnARR: logoChurnMRR * 12, contractionARR: contractionMRR * 12
    };
  }

  /* v2 Gate B — the monetization sub-record of a cohort row. Per-customer
     revenue is ANNUAL (the unit the components are priced in); cohort flows
     are ARR readouts of the MRR quantities the transition produced. */
  var moRatesFor = function (state) {   /* fixed/variable split needs only the kind, carried on the state */
    return state.map(function (k) { return { fixed: !!k.fixed, unitsCap: k.unitsCap === undefined ? null : k.unitsCap, penetrationCap: k.penetrationCap === undefined ? 1 : k.penetrationCap }; });
  };
  function monetizationRow(n, stateOpen, stateClose, r, tr) {
    var rv = MO.revenue(stateClose, r);
    return {
      perCustomerOpening: MO.revenue(stateOpen, r).total, perCustomerClosing: rv.total,
      fixedARR: n * rv.fixed, variableARR: n * rv.variable,
      priceARR: tr ? n * tr.effects.price : 0, usageARR: tr ? n * tr.effects.usage : 0, adoptionARR: tr ? n * tr.effects.adoption : 0,
      contractionARR: tr ? n * tr.effects.contraction : 0,
      headroom: tr ? tr.headroom : null,
      state: MO.copyState(stateClose)
    };
  }

  /* ------------------------------------------------------------------ *
   * The engine
   * ------------------------------------------------------------------ */
  function run(assumptions, start, horizon) {
    var a = normaliseAssumptions(assumptions);
    var s = Object.assign({}, DEFAULT_START, start || {});
    var H = horizon || HORIZON;

    /* v2 Gate A — CUSTOMER PHYSICS. When on, the cohort transition is
       generated by customers.js and persistenceAnnual is NOT READ: the
       effective annual persistence P is DERIVED, P = L(1 − C). When off (the
       null world) every line below is the v1.3 line. */
    var CUON = CU.enabled(a);
    var cuR = CUON ? CU.rates(a) : null;   /* named apart from the loop scalars below */
    var P = CUON ? cuR.impliedPersistenceAnnual : a.persistenceAnnual;
    var aEff = CUON ? Object.assign({}, a, { persistenceAnnual: P }) : a;
    /* v2 Gate B — MONETIZATION PHYSICS. When on, a cohort's revenue is DERIVED
       from per-customer components every month; the generic expansion
       coefficient, newLogoARPA and start.openingARR are NOT READ. Contraction
       reaches variable revenue only, so persistence is EMERGENT (mix-dependent),
       not the Gate A constant. Requires Customer Physics (validated). */
    var MON = MO.enabled(a);
    var moSpec = MON ? a.monetization : null;
    var moR = MON ? MO.rates(moSpec) : null;
    /* the per-customer state carries its component kind and caps so a row's
       fixed/variable split can be read without the spec */
    function stampKinds(state) { return state.map(function (k, i) { return { penetration: k.penetration, units: k.units, price: k.price, fixed: moR[i].fixed, unitsCap: moR[i].unitsCap, penetrationCap: moR[i].penetrationCap }; }); }
    var moInitial = MON ? stampKinds(MO.initialState(moSpec)) : null;
    var moNewLogoRevenue = MON ? MO.revenue(moInitial, moR).total : null;

    var gM = MON ? null : toMonthlyPersistence(P);
    var eM = MON ? null : toMonthlyExpansion(a.expansionCoefficientAnnual);
    /* MRR-NATIVE: the state the engine carries forward each month is newMRR;
       newARR (still newARRPerMonth(a), v1.2: through the saturating response)
       is kept as the exact 12x-derived reporting figure every existing caller
       reads. It is the LAW's output per month of spend; what actually enters
       the stock in month t is the realised amount below (v1.3). */
    var newARR = newARRPerMonth(a);
    var newMRR = newARR / 12;
    var LAG = a.acquisitionLagMonths;            /* validated: integer >= 0 */
    /* v1.3 PENDING ACQUISITION — explicit engine state. Every month of spend
       creates one ledger entry; it matures into a cohort at spendMonth + LAG.
       The ledger is returned whole (res.acquisitionLedger) so provenance and
       reconciliation are inspectable, never inferred from a shifted chart.
       Each entry carries the ACQUISITION LAW IN FORCE AT SPEND (coefficient,
       capacity) as well as the amount it produced — the cohort it becomes is
       stamped from the entry, never from the live assumptions at maturity. */
    var ledger = [], pending = [];

    var bands = resolveBands(aEff);
    var bandRates = bands.map(function (b) {
      return { name: b.name, maxAgeExclusive: b.maxAgeExclusive,
               persistenceAnnual: b.persistenceAnnual,
               expansionCoefficientAnnual: b.expansionCoefficientAnnual,
               g: toMonthlyPersistence(b.persistenceAnnual),
               e: toMonthlyExpansion(b.expansionCoefficientAnnual) };
    });

    /* 4. The company IS a set of cohorts. Aggregates are only ever sums.
       v0.3: the opening base may be several vintages of different ages. */
    var seed = (s.openingCohorts && s.openingCohorts.length)
      ? s.openingCohorts
      : [{ arr: s.openingARR, age: 0, customers: s.openingCustomers }];
    /* v2 Gate B: opening ARR is DERIVED — customers × per-customer revenue of
       the opening components. The arr the caller passed is reported, not read. */
    var openingARRInputIgnored = null;
    if (MON) {
      openingARRInputIgnored = seed.reduce(function (q, c) { return q + (c.arr || 0); }, 0);
      seed = seed.map(function (c) {
        if (typeof c.customers !== 'number' || !(c.customers > 0))
          throw new RangeError('Monetization Physics is on: every opening cohort needs customers > 0 (got ' + String(c.customers) + ')');
        return Object.assign({}, c, { arr: c.customers * moNewLogoRevenue });
      });
    }
    var openingARRUsed = seed.reduce(function (q, c) { return q + c.arr; }, 0);
    /* v2 Gate A: opening customers, opening ARPA, and the € ARR per new logo
       (input, or the opening ARPA when null). Read only when the layer is on. */
    var openingCustomersTotal = null, openingARPA = null, newLogoARPA = null, newLogoARPASource = null;
    if (CUON) {
      openingCustomersTotal = 0;
      seed.forEach(function (c, i) {
        if (typeof c.customers !== 'number' || !(c.customers > 0))
          throw new RangeError('Customer Physics is on: opening cohort ' + (i + 1) + ' needs customers > 0 (got ' + String(c.customers) + ')');
        openingCustomersTotal += c.customers;
      });
      var seedARR = seed.reduce(function (q, c) { return q + c.arr; }, 0);
      openingARPA = seedARR / openingCustomersTotal;
      if (MON) { newLogoARPA = moNewLogoRevenue; newLogoARPASource = 'monetization: per-customer components'; }
      else if (a.newLogoARPA !== null) { newLogoARPA = a.newLogoARPA; newLogoARPASource = 'input'; }
      else { newLogoARPA = openingARPA; newLogoARPASource = 'opening ARPA'; }
    }
    var cohorts = seed.map(function (c, i) {
      return {
        id: seed.length === 1 ? 'base' : 'base' + (i + 1),
        label: c.label || (seed.length === 1 ? 'Opening base' : 'Opening vintage, age ' + c.age),
        acquisitionMonth: 0,
        initialAge: c.age || 0,
        initialARR: c.arr,
        /* MRR-NATIVE: c.arr is the public, ARR-denominated seed input
           (unchanged API); live is the engine's own state, carried in MRR. */
        live: c.arr / 12,
        /* PROVENANCE. The cost of creating the opening base happened before the
           simulation and is genuinely unknown — recorded as null, never as zero. */
        acquisitionCost: null,
        cacPerARRAtCreation: null,
        /* v2 Gate A — customer state; null = Customer Physics off */
        initialCustomers: CUON ? c.customers : null,
        customers: CUON ? c.customers : null,
        /* v2 Gate B — per-customer component state; null = Monetization off */
        money: MON ? MO.copyState(moInitial) : null,
        rows: []
      };
    });

    var months = [];
    var cash = s.openingCash;
    var nrrMonthlyHistory = [];
    var cum = { newARR: 0, expansion: 0, leakage: 0, revenue: 0, cogs: 0,
                grossProfit: 0, sm: 0, rd: 0, ga: 0, expansionCost: 0, ebita: 0, fcf: 0 };

    function closingAt(k) { return k === 0 ? openingARRUsed : months[k - 1].closingARR; }

    /* v2 Gate A cumulative customer flows (kept apart from the v1.3 cum object) */
    var cumCu = { logoChurnARR: 0, contractionARR: 0, newCustomers: 0, logoChurnCustomers: 0 };
    var cumMo = { priceARR: 0, usageARR: 0, adoptionARR: 0 };

    for (var t = 1; t <= H; t++) {
      var openingMRR = 0, i, c;
      for (i = 0; i < cohorts.length; i++) openingMRR += cohorts[i].live;

      var totRetainedMRR = 0, totLeakageMRR = 0, totExpansionMRR = 0, totRevenue = 0, totExpansionCost = 0;
      var cuOpen = 0, cuClose = 0, cuLogoChurnMRR = 0, cuContractionMRR = 0;
      var moPriceMRR = 0, moUsageMRR = 0, moAdoptMRR = 0, moFixedMRR = 0, moVarMRR = 0;

      /* --- 5. MRR physics, applied cohort by cohort (MRR-NATIVE) ---
         Same transition coefficients, same order, same identities as before —
         only the unit the state is carried in changed, from ARR to MRR. ARR
         fields below are kept for every existing reader, each now DERIVED as
         exactly 12 x the MRR quantity computed the same month.
         v0.3: the coefficients used are those of the band the cohort occupies at
         the START of the month. Nothing else about the transition changed. */
      for (i = 0; i < cohorts.length; i++) {
        c = cohorts[i];
        var ageEnd     = c.initialAge + (t - c.acquisitionMonth);
        var ageAtStart = ageEnd - 1;
        var bi = bandFor(bandRates, ageAtStart);
        var br = bandRates[bi];
        var openingC  = c.live;
        var retainedC, leakageC, expansionC, closingC, cuRow = null, moRow = null;
        if (MON) {
          /* v2 Gate B — logo churn from customers.js; survivor revenue from the
             per-customer components: contraction (variable units) → price →
             usage (to cap) → adoption (to cap). The generic expansion
             coefficient is BYPASSED: expansion = price + usage + adoption. */
          var trc = CU.transition({ n: c.customers, mrr: openingC }, cuR);
          var mt = MO.transition(c.money, moR, cuR.cM);
          var n1 = trc.customersClosing;
          var contrC = n1 * mt.effects.contraction / 12;
          var priceC = n1 * mt.effects.price / 12, usageC = n1 * mt.effects.usage / 12, adoptC = n1 * mt.effects.adoption / 12;
          retainedC = trc.survivorMRR - contrC; leakageC = trc.logoChurnMRR + contrC;
          expansionC = priceC + usageC + adoptC; closingC = retainedC + expansionC;
          cuRow = customerRow(trc.customersOpening, n1, trc.logoChurnMRR, contrC, trc.survivorMRR);
          var stateClose = stampKinds(mt.state);
          moRow = monetizationRow(n1, c.money, stateClose, moR, mt);
          c.money = stateClose; c.customers = n1;
          cuOpen += trc.customersOpening; cuClose += n1;
          cuLogoChurnMRR += trc.logoChurnMRR; cuContractionMRR += contrC;
          moPriceMRR += priceC; moUsageMRR += usageC; moAdoptMRR += adoptC;
          moFixedMRR += moRow.fixedARR / 12; moVarMRR += moRow.variableARR / 12;
        } else if (CUON) {
          /* v2 Gate A — the transition is GENERATED by customer mechanics:
             logo survival, then contraction among survivors, then expansion
             among survivors. leakage = logo churn + contraction; the v1.3
             identity closing = opening × g × (1 + e) holds with g = l(1 − c). */
          var tr = CU.transition({ n: c.customers, mrr: openingC }, cuR);
          retainedC = tr.retainedMRR; leakageC = tr.leakageMRR;
          expansionC = tr.expansionMRR; closingC = tr.closingMRR;
          cuRow = customerRow(tr.customersOpening, tr.customersClosing, tr.logoChurnMRR, tr.contractionMRR, tr.survivorMRR);
          c.customers = tr.customersClosing;
          cuOpen += tr.customersOpening; cuClose += tr.customersClosing;
          cuLogoChurnMRR += tr.logoChurnMRR; cuContractionMRR += tr.contractionMRR;
        } else {
          retainedC = openingC * br.g;            // persistence can only shrink or hold
          leakageC  = openingC - retainedC;        // churn + contraction combined
          expansionC= retainedC * br.e;            // expansion applies to RETAINED MRR
          closingC  = retainedC + expansionC;
        }
        var avgMRR    = (openingC + closingC) / 2;   // 7. stock -> flow
        var revenue   = avgMRR;                       // MRR already IS the monthly amount
        var gp        = revenue * a.grossMargin;
        /* v1.1 EXPANSION REALISATION COST — priced on the expansion ARR the
           transition above ALREADY produced. Read by nothing in the transition:
           it is computed after closingC and never feeds c.live, so retained,
           expansion, closing, GRR and NRR are provably untouched by it. */
        var expCostC  = expansionC * 12 * a.expansionCostPerARR;

        c.rows.push({
          t: t, age: ageEnd, ageAtStart: ageAtStart, band: bi, bandName: br.name,
          openingMRR: openingC, retainedMRR: retainedC, leakageMRR: leakageC,
          expansionMRR: expansionC, closingMRR: closingC,
          openingARR: openingC * 12, retainedARR: retainedC * 12, leakage: leakageC * 12,
          expansion: expansionC * 12, closingARR: closingC * 12,
          revenue: revenue, grossProfit: gp, expansionCost: expCostC,
          customers: cuRow,                         /* v2 Gate A; null when off */
          monetization: moRow                       /* v2 Gate B; null when off */
        });
        c.live = closingC;

        totRetainedMRR += retainedC; totLeakageMRR += leakageC;
        totExpansionMRR += expansionC; totRevenue += revenue; totExpansionCost += expCostC;
      }

      /* --- v1.3 SPEND. S&M is incurred NOW (it hits EBITA and cash below in
         this month) and enters the pending ledger with the New ARR the law IN
         FORCE NOW says it will create, dated to mature at t + LAG. --- */
      var entry = pendingEntry(a, t, LAG, newARR, newLogoARPA, moInitial);
      ledger.push(entry); pending.push(entry);

      /* --- v1.3 REALISE. Whatever matured this month becomes the acquisition
         cohort, created AFTER the base has aged (the same order as v1.0). With
         LAG = 0 the entry just written matures immediately, which is exactly
         the v1.0 same-month world. When NOTHING matures (the first LAG months
         of a lagged world) NO cohort is created: a customer cohort that does
         not yet exist is not represented by a zero-ARR placeholder — the spend
         is in the pending stock, which is where it economically is. Entries
         maturing beyond the horizon stay pending forever — spend near the end
         of the window never magically appears inside it. --- */
      var matured = [];
      for (i = pending.length - 1; i >= 0; i--) {
        if (pending[i].matureMonth === t) matured.push(pending.splice(i, 1)[0]);
      }
      var realisedARR = 0, realisedMRR = 0, realisedCustomers = 0;
      if (matured.length) {
        var nc = realiseCohort(t, matured, bandRates[0].name, a.grossMargin);
        realisedARR = nc.initialARR; realisedMRR = nc.live;
        if (CUON) { realisedCustomers = nc.customers; cuClose += nc.customers; }
        if (MON) { moFixedMRR += nc.rows[0].monetization.fixedARR / 12; moVarMRR += nc.rows[0].monetization.variableARR / 12; }
        cohorts.push(nc);
        totRevenue += nc.rows[0].revenue;
      }

      var pendingARR = 0, pendingSpend = 0;
      for (i = 0; i < pending.length; i++) { pendingARR += pending[i].newARR; pendingSpend += pending[i].sm; }

      var closingMRR = totRetainedMRR + totExpansionMRR + realisedMRR;

      /* --- 7/8. Revenue and gross profit (company = sum of cohorts) --- */
      var avgMRRco  = (openingMRR + closingMRR) / 2;
      var revenue   = avgMRRco;              // MRR-NATIVE: no /12 — MRR is already monthly
      var cogs      = revenue * (1 - a.grossMargin);
      var grossProfit = revenue * a.grossMargin;

      /* --- 9. EBITA. v1.1: less the expansion realisation cost, a named line
         of its own (company total = Σ cohort expansionCost, by construction). --- */
      var expansionCost = totExpansionCost;
      var ebita = grossProfit - a.sm - a.rd - a.ga - expansionCost;

      /* --- 10. Cash. FCF = EBITA in v0.1 (no WC/tax/capex). Disclosed. --- */
      var fcf = ebita;
      var cashOpening = cash;
      var cashClosing = cashOpening + fcf;
      cash = cashClosing;

      /* --- 11. NRR: eligible OPENING installed base only, New MRR excluded ---
         Ratio of same-unit MRR quantities — numerically identical whichever
         scale (MRR or ARR) it is taken in, so unaffected by the refactor. */
      var nrrMonthly = openingMRR > 0 ? (totRetainedMRR + totExpansionMRR) / openingMRR : 1;
      nrrMonthlyHistory.push(nrrMonthly);
      var window = nrrMonthlyHistory.slice(-12);
      var prod = window.reduce(function (p, x) { return p * x; }, 1);
      var nrrAnnualised = Math.pow(prod, 12 / window.length);

      var openingARR = openingMRR * 12, closingARR = closingMRR * 12;
      var totRetainedARR = totRetainedMRR * 12, totLeakageARR = totLeakageMRR * 12, totExpansionARR = totExpansionMRR * 12;

      cum.newARR += realisedARR; cum.expansion += totExpansionARR; cum.leakage += totLeakageARR;
      cum.revenue += revenue; cum.cogs += cogs; cum.grossProfit += grossProfit;
      cum.sm += a.sm; cum.rd += a.rd; cum.ga += a.ga; cum.expansionCost += expansionCost;
      cum.ebita += ebita; cum.fcf += fcf;

      /* v2 Gate A — the company customer record: sums of the cohort sub-records */
      var cuRec = null;
      if (CUON) {
        cumCu.logoChurnARR += cuLogoChurnMRR * 12; cumCu.contractionARR += cuContractionMRR * 12;
        cumCu.newCustomers += realisedCustomers; cumCu.logoChurnCustomers += cuOpen - (cuClose - realisedCustomers);
        cuRec = {
          opening: cuOpen, closing: cuClose, logoChurn: cuOpen - (cuClose - realisedCustomers),
          newCustomers: realisedCustomers,
          logoChurnMRR: cuLogoChurnMRR, contractionMRR: cuContractionMRR,
          logoChurnARR: cuLogoChurnMRR * 12, contractionARR: cuContractionMRR * 12,
          arpaOpening: cuOpen > 0 ? openingMRR * 12 / cuOpen : null,
          arpaClosing: cuClose > 0 ? closingMRR * 12 / cuClose : null,
          cumulative: Object.assign({}, cumCu)
        };
      }

      /* v2 Gate B — the company monetization record: sums of the cohort sub-records */
      var moRec = null;
      if (MON) {
        cumMo.priceARR += moPriceMRR * 12; cumMo.usageARR += moUsageMRR * 12; cumMo.adoptionARR += moAdoptMRR * 12;
        moRec = {
          fixedARR: moFixedMRR * 12, variableARR: moVarMRR * 12,
          variableShare: closingMRR > 0 ? moVarMRR / closingMRR : 0,
          priceARR: moPriceMRR * 12, usageARR: moUsageMRR * 12, adoptionARR: moAdoptMRR * 12,
          contractionARR: cuContractionMRR * 12,
          cumulative: Object.assign({}, cumMo)
        };
      }

      months.push({
        t: t,
        year: Math.ceil(t / 12),
        quarter: Math.ceil(t / 3),
        /* MRR-NATIVE state (the engine's own quantities) */
        openingMRR: openingMRR,
        retainedMRR: totRetainedMRR,
        leakageMRR: totLeakageMRR,
        expansionMRR: totExpansionMRR,
        newMRR: realisedMRR,
        closingMRR: closingMRR,
        avgMRR: avgMRRco,
        /* ARR — DERIVED reporting view, ARR = 12 x MRR, exactly */
        openingARR: openingARR,
        retainedARR: totRetainedARR,
        leakage: totLeakageARR,
        expansion: totExpansionARR,
        newARR: realisedARR,                   /* realised this month (v1.3) */
        closingARR: closingARR,
        /* v1.3 — the pending-acquisition stock at the END of this month, and
           what left it. All zero in the null world. */
        acquisitionLawNewARR: newARR,          /* what this month's spend will create, when it matures */
        pendingNewARR: pendingARR,
        pendingSpend: pendingSpend,
        pendingCount: pending.length,
        realisedFromSpendMonth: matured.length ? matured[matured.length - 1].spendMonth : null,
        cohortCreated: matured.length > 0,
        cohortRevenueSum: totRevenue,
        avgARR: avgMRRco * 12,
        revenue: revenue,
        cogs: cogs,
        grossProfit: grossProfit,
        sm: a.sm, rd: a.rd, ga: a.ga,
        expansionCost: expansionCost,          /* v1.1 — 0 in the null world */
        ebita: ebita,
        ebitaMargin: revenue > 0 ? ebita / revenue : 0,
        fcf: fcf,
        burn: fcf < 0 ? -fcf : 0,
        cashOpening: cashOpening,
        cashClosing: cashClosing,
        nrrMonthly: nrrMonthly,               /* chained transition NRR, not the R12M KPI */
        nrrAnnualised: nrrAnnualised,         /* chained monthly NRR annualised — see kpi.js for the KPI */
        arrGrowthMoM: openingARR > 0 ? closingARR / openingARR - 1 : 0,
        arrGrowthYoY: t >= 12 ? closingARR / closingAt(t - 12) - 1 : null,
        cohortCount: cohorts.length,
        cumulative: Object.assign({}, cum),
        customers: cuRec,                      /* v2 Gate A; null = Customer Physics off */
        monetization: moRec                    /* v2 Gate B; null = Monetization off */
      });
    }

    var acq = acquisitionResponse(a);

    /* --- Cohort cumulatives --- */
    for (var k = 0; k < cohorts.length; k++) {
      var co = cohorts[k];
      var cl = 0, ce = 0, cr = 0, cg = 0, cx = 0;
      for (var r = 0; r < co.rows.length; r++) {
        cl += co.rows[r].leakage; ce += co.rows[r].expansion;
        cr += co.rows[r].revenue; cg += co.rows[r].grossProfit; cx += co.rows[r].expansionCost;
        co.rows[r].cumLeakage = cl; co.rows[r].cumExpansion = ce;
        co.rows[r].cumRevenue = cr; co.rows[r].cumGrossProfit = cg; co.rows[r].cumExpansionCost = cx;
      }
      co.cumLeakage = cl; co.cumExpansion = ce;
      co.cumRevenue = cr; co.cumGrossProfit = cg; co.cumExpansionCost = cx;
      co.finalMRR = co.live;
      co.finalARR = co.live * 12;
      co.finalCustomers = CUON ? co.customers : null;
      co.finalPerCustomerRevenue = MON ? MO.revenue(co.money, moR).total : null;
    }
    /* v2 Gate B — the emergent monthly multiplier of the opening base in its
       first month (closing ÷ opening), for readers that framed the regime on
       g = persistence × (1 + expansion) — under Monetization neither is a law */
    var emergentG = (cohorts[0].rows.length && cohorts[0].rows[0].openingMRR > 0) ? cohorts[0].rows[0].closingMRR / cohorts[0].rows[0].openingMRR : null;

    return {
      modelVersion: '2.0',
      /* which mechanisms are actually switched on in this run */
      mechanisms: {
        expansionCost: a.expansionCostPerARR > 0,
        acquisitionSaturation: saturationEnabled(a),
        acquisitionLag: a.acquisitionLagMonths > 0,
        customerPhysics: CUON,                      /* v2 Gate A */
        monetization: MON,                          /* v2 Gate B */
        genericExpansionBypassed: MON               /* v2 Gate B: expansionCoefficientAnnual not read */
      },
      assumptions: a,
      start: s,
      horizon: H,
      bands: bandRates,
      bandsAreFlat: bandRates.every(function (b) {
        return b.persistenceAnnual === bandRates[0].persistenceAnnual &&
               b.expansionCoefficientAnnual === bandRates[0].expansionCoefficientAnnual;
      }),
      derived: {
        monthlyPersistence: gM,
        monthlyExpansion: eM,
        newMRRPerMonth: newMRR,                       // € of MRR the law creates per month of spend — MRR-NATIVE
        newARRPerMonth: newARR,                       // € of ARR the law creates per month of spend — DERIVED, = 12 x newMRR
        newARRAnnualised: newARR * 12,                // € of ARR created per year of spend
        annualAcquisitionSpend: a.sm * 12,
        cacPerMRR: cacPerMRR(a),                      // € of S&M per €1 of New MRR — DERIVED, = cacPerARR x 12
        cacPaybackMonths: cacPaybackMonths(a),        // EMERGENT — the coefficient's own payback, unchanged value
        impliedAnnualNRR: MON ? null : P * (1 + a.expansionCoefficientAnnual),
        /* v2 Gate A — the persistence actually in force, and where it came from.
           v2 Gate B — under Monetization neither persistence nor expansion is a
           law: both are emergent from the component state and its mix. */
        persistenceAnnualEffective: MON ? null : P,
        persistenceSource: MON ? 'emergent: monetization (contraction reaches variable revenue only)' : CUON ? 'derived: L(1 - C)' : 'input',
        expansionSource: MON ? 'emergent: price + usage + adoption (generic coefficient bypassed)' : 'input',
        emergentMonthlyMultiplier: emergentG,
        monetization: MON ? {
          spec: moSpec,
          newLogoRevenuePerCustomer: moNewLogoRevenue,
          openingARRDerived: openingARRUsed,
          openingARRInputIgnored: openingARRInputIgnored,
          expansionCoefficientIgnored: a.expansionCoefficientAnnual,
          newLogoARPAIgnored: a.newLogoARPA,
          customerLawPersistence: P,             /* L(1 − C): what persistence WOULD be if contraction reached all revenue */
          monthlyRates: moR
        } : null,
        customers: CUON ? {
          logoRetentionAnnual: a.logoRetentionAnnual, contractionAnnual: a.contractionAnnual,
          monthlyLogoRetention: cuR.l, monthlyContraction: cuR.cM,
          impliedPersistenceAnnual: cuR.impliedPersistenceAnnual,
          persistenceInputIgnored: a.persistenceAnnual,
          openingCustomers: openingCustomersTotal, openingARPA: openingARPA,
          newLogoARPA: newLogoARPA, newLogoARPASource: newLogoARPASource
        } : null,
        impliedCACPerNewARR: newARR > 0 ? a.sm / newARR : 0,  // reconciles to cacPerARR while the bound is off; the AVERAGE CAC when it is on
        /* v1.2 — the acquisition response at this run's S&M, analytically */
        acquisition: acq,
        /* v1.3 — timing */
        acquisitionLagMonths: LAG,
        /* v1.1 — what expansion realisation costs in this world */
        expansionCostPerARR: a.expansionCostPerARR
      },
      months: months,
      cohorts: cohorts,
      /* v1.3 — the whole pending-acquisition ledger, and what is still pending
         at the horizon (spend whose ARR never appears inside the window) */
      acquisitionLedger: ledger,
      pendingAtHorizon: {
        entries: pending.slice(),
        newARR: pending.reduce(function (s, e) { return s + e.newARR; }, 0),
        spend: pending.reduce(function (s, e) { return s + e.sm; }, 0)
      }
    };
  }

  /* ------------------------------------------------------------------ *
   * Read helpers used by both the UI and the reports
   * ------------------------------------------------------------------ */
  function bridge(res, t) {
    var m = res.months[t - 1];
    return {
      t: t,
      openingARR: m.openingARR,
      newARR: m.newARR,
      expansion: m.expansion,
      leakage: m.leakage,
      closingARR: m.closingARR,
      residual: m.openingARR + m.newARR + m.expansion - m.leakage - m.closingARR
    };
  }

  function cohortSnapshot(res, t) {
    var out = [];
    for (var i = 0; i < res.cohorts.length; i++) {
      var c = res.cohorts[i];
      if (c.acquisitionMonth > t) continue;
      /* base cohort rows start at t=1; acquisition cohorts start at t=acquisitionMonth */
      var idx = c.acquisitionMonth === 0 ? t - 1 : t - c.acquisitionMonth;
      var row = c.rows[idx];
      if (!row) continue;
      out.push({
        id: c.id,
        acquisitionMonth: c.acquisitionMonth,
        bandName: row.bandName,
        acquisitionCost: c.acquisitionCost,
        cacPerARRAtCreation: c.cacPerARRAtCreation,
        cacCoefficientAtCreation: c.cacCoefficientAtCreation === undefined ? null : c.cacCoefficientAtCreation,
        capacityAtSpend: c.capacityAtSpend === undefined ? null : c.capacityAtSpend,
        spendMonth: c.spendMonth === undefined ? null : c.spendMonth,
        lagMonths: c.lagMonths === undefined ? null : c.lagMonths,
        age: row.age,
        initialARR: c.initialARR,
        openingARR: row.openingARR,
        currentARR: row.closingARR,
        leakage: row.leakage,
        expansion: row.expansion,
        cumLeakage: row.cumLeakage,
        cumExpansion: row.cumExpansion,
        cumRevenue: row.cumRevenue,
        cumGrossProfit: row.cumGrossProfit,
        expansionCost: row.expansionCost,
        cumExpansionCost: row.cumExpansionCost,
        retainedShare: c.initialARR > 0 ? row.closingARR / c.initialARR : 0,
        /* v2 Gate A — customer state at t; null = Customer Physics off */
        initialCustomers: c.initialCustomers === undefined ? null : c.initialCustomers,
        customers: row.customers ? row.customers.closing : null,
        logoChurnARR: row.customers ? row.customers.logoChurnARR : null,
        contractionARR: row.customers ? row.customers.contractionARR : null,
        arpa: row.customers && row.customers.closing > 0 ? row.closingARR / row.customers.closing : null,
        /* v2 Gate B — per-customer revenue and its composition; null = Monetization off */
        perCustomerRevenue: row.monetization ? row.monetization.perCustomerClosing : null,
        fixedARR: row.monetization ? row.monetization.fixedARR : null,
        variableARR: row.monetization ? row.monetization.variableARR : null,
        priceARR: row.monetization ? row.monetization.priceARR : null,
        usageARR: row.monetization ? row.monetization.usageARR : null,
        adoptionARR: row.monetization ? row.monetization.adoptionARR : null,
        headroom: row.monetization ? row.monetization.headroom : null,
        perCustomerState: row.monetization ? row.monetization.state : null
      });
    }
    return out;
  }

  /* ARR mix at month t: opening base vs cohorts by acquisition year */
  function arrMix(res, t) {
    var snap = cohortSnapshot(res, t);
    var total = snap.reduce(function (s, c) { return s + c.currentARR; }, 0);
    var buckets = { base: 0, y1: 0, y2: 0, y3: 0, y4: 0, y5: 0 };
    snap.forEach(function (c) {
      if (c.acquisitionMonth === 0) buckets.base += c.currentARR;
      else buckets['y' + Math.ceil(c.acquisitionMonth / 12)] += c.currentARR;
    });
    var shares = {};
    Object.keys(buckets).forEach(function (k) { shares[k] = total > 0 ? buckets[k] / total : 0; });
    return { total: total, amounts: buckets, shares: shares };
  }

  /* ------------------------------------------------------------------ *
   * Rate-conversion diagnostics (brief §8).
   *
   * The engine converts both annual rates geometrically and applies expansion to
   * RETAINED ARR, so monthly NRR = mGRR x (1 + mExp) and twelve of those compound
   * to exactly GRR x (1 + expansion). The intended annual NRR is reproduced exactly.
   *
   * What is NOT reproduced exactly is the DECOMPOSITION. A CFO measures annual gross
   * retention as (leakage over the year / opening ARR) and annual expansion as
   * (expansion over the year / opening ARR). Both of those flows accrue on a base
   * that moves during the year, and expansion accrues on the post-churn base, so the
   * measured rates differ from the input rates even though their net effect does not.
   * This function reports both so the gap is visible rather than assumed away.
   * ------------------------------------------------------------------ */
  function rateDiagnostics(res) {
    var a = res.assumptions, gM = res.derived.monthlyPersistence, eM = res.derived.monthlyExpansion;
    var base = res.cohorts[0], rows = base.rows.slice(0, 12);
    var opening = base.initialARR;
    var leak = 0, exp = 0;
    rows.forEach(function (r) { leak += r.leakage; exp += r.expansion; });
    var closing = rows.length ? rows[rows.length - 1].closingARR : opening;
    return {
      inputPersistenceAnnual: a.persistenceAnnual,
      inputExpansionCoefficient: a.expansionCoefficientAnnual,
      monthlyPersistence: gM,
      monthlyExpansion: eM,
      monthlyNRR: gM * (1 + eM),
      twelveMonthPersistence: Math.pow(gM, 12),                 // = input GRR
      twelveMonthExpansionCoefficient: Math.pow(1 + eM, 12) - 1,   // = input expansion
      twelveMonthNRRCompounded: Math.pow(gM * (1 + eM), 12),      // = GRR x (1 + expansion)
      /* measured the way a finance team would, from the first 12 months of the
         opening cohort's actual flows. See kpi.js for the general R12M measurement. */
      realisedGrossRetention: opening > 0 ? 1 - leak / opening : 1,
      realisedExpansionRate: opening > 0 ? exp / opening : 0,
      realisedNRR: opening > 0 ? closing / opening : 1,
      realisedLeakage: leak,
      realisedExpansion: exp
    };
  }

  /* ------------------------------------------------------------------ *
   * 14. Explainability — every number below comes out of the simulation,
   * none of it is asserted prose. Shared by the report and the UI.
   * ------------------------------------------------------------------ */
  function summarise(res) {
    var last = res.months[res.horizon - 1];
    var y5 = yearSlice(res, Math.ceil(res.horizon / 12));
    var cum = last.cumulative;
    var trough = res.months.reduce(function (lo, m) { return m.cashClosing < lo.cashClosing ? m : lo; }, res.months[0]);
    var firstProfit = null, firstOutOfCash = null;
    for (var i = 0; i < res.months.length; i++) {
      if (firstProfit === null && res.months[i].ebita > 0) firstProfit = res.months[i].t;
      if (firstOutOfCash === null && res.months[i].cashClosing < 0) firstOutOfCash = res.months[i].t;
    }
    var mix = arrMix(res, res.horizon);
    function arrAtYear(y) { var i = y * 12 - 1; return i < res.months.length ? res.months[i].closingARR : null; }
    return {
      newARRPerMonth: res.derived.newARRPerMonth,
      cacPaybackMonths: res.derived.cacPaybackMonths,
      y1ARR: arrAtYear(1), y3ARR: arrAtYear(3),
      openingCohortARR: mix.amounts.base,
      acquiredCohortARR: mix.total - mix.amounts.base,
      finalARR: last.closingARR,
      finalNRR: last.nrrAnnualised,
      finalGrowthYoY: last.arrGrowthYoY,
      cumNewARR: cum.newARR,
      cumExpansion: cum.expansion,
      cumLeakage: cum.leakage,
      cumRevenue: cum.revenue,
      cumGrossProfit: cum.grossProfit,
      cumExpansionCost: cum.expansionCost,
      cumEbita: cum.ebita,
      cumSM: cum.sm,
      finalYearFCF: y5.fcf,
      finalYearGrossProfit: y5.grossProfit,
      finalYearEbitaMargin: y5.ebitaMargin,
      endingCash: last.cashClosing,
      cashTrough: trough.cashClosing,
      cashTroughMonth: trough.t,
      cohortCount: res.cohorts.length,
      /* v1.2 / v1.3 — acquisition economics and timing, read from derived/ledger */
      averageCAC: res.derived.acquisition.averageCAC,
      marginalCAC: res.derived.acquisition.marginalCAC,
      acquisitionUtilisation: res.derived.acquisition.utilisation,
      firstCohortMonth: (function () {
        for (var q = 0; q < res.months.length; q++) if (res.months[q].newARR > 0) return res.months[q].t;
        return null;
      })(),
      pendingNewARRAtHorizon: res.pendingAtHorizon.newARR,
      pendingSpendAtHorizon: res.pendingAtHorizon.spend,
      firstProfitableMonth: firstProfit,
      firstNegativeCashMonth: firstOutOfCash,
      baseCohortShare: mix.shares.base,
      mix: mix,
      /* v2 Gate A — customer readouts; null = Customer Physics off */
      finalCustomers: last.customers ? last.customers.closing : null,
      finalARPA: last.customers ? last.customers.arpaClosing : null,
      cumNewCustomers: last.customers ? last.customers.cumulative.newCustomers : null,
      cumLogoChurnCustomers: last.customers ? last.customers.cumulative.logoChurnCustomers : null,
      cumLogoChurnARR: last.customers ? last.customers.cumulative.logoChurnARR : null,
      cumContractionARR: last.customers ? last.customers.cumulative.contractionARR : null,
      /* v2 Gate B — monetization readouts; null = Monetization off */
      finalVariableShare: last.monetization ? last.monetization.variableShare : null,
      cumPriceARR: last.monetization ? last.monetization.cumulative.priceARR : null,
      cumUsageARR: last.monetization ? last.monetization.cumulative.usageARR : null,
      cumAdoptionARR: last.monetization ? last.monetization.cumulative.adoptionARR : null
    };
  }

  function compare(baseRes, expRes) {
    var b = summarise(baseRes), x = summarise(expRes);
    var delta = {};
    Object.keys(b).forEach(function (k) {
      if (typeof b[k] === 'number' && typeof x[k] === 'number') delta[k] = x[k] - b[k];
    });
    var changed = [];
    Object.keys(expRes.assumptions).forEach(function (k) {
      if (k === 'bands') return;                       // structural, compared separately
      if (k === 'monetization') {                      // v2 Gate B: a nested spec — compared leaf by leaf
        var bm = baseRes.assumptions[k], xm = expRes.assumptions[k];
        if (bm === xm) return;
        if (!bm || !xm) { changed.push({ key: k, from: bm ? 'on' : null, to: xm ? 'on' : null }); return; }
        var n = Math.max(bm.components.length, xm.components.length);
        for (var ci = 0; ci < n; ci++) {
          var bc = bm.components[ci], xc = xm.components[ci];
          if (!bc || !xc) { changed.push({ key: k + '.components[' + ci + ']', from: bc || null, to: xc || null }); continue; }
          Object.keys(xc).forEach(function (f) { if (xc[f] !== bc[f]) changed.push({ key: k + '.components[' + ci + '].' + f, from: bc[f], to: xc[f] }); });
        }
        return;
      }
      if (expRes.assumptions[k] !== baseRes.assumptions[k]) {
        changed.push({ key: k, from: baseRes.assumptions[k], to: expRes.assumptions[k] });
      }
    });
    var bandsChanged = JSON.stringify(baseRes.bands.map(function (bb) {
      return [bb.persistenceAnnual, bb.expansionCoefficientAnnual]; })) !==
      JSON.stringify(expRes.bands.map(function (bb) {
        return [bb.persistenceAnnual, bb.expansionCoefficientAnnual]; }));
    return { base: b, experiment: x, delta: delta, changed: changed, bandsChanged: bandsChanged };
  }

  function yearSlice(res, year) {
    var ms = res.months.filter(function (m) { return m.year === year; });
    var last = ms[ms.length - 1];
    var sum = function (k) { return ms.reduce(function (s, m) { return s + m[k]; }, 0); };
    return {
      year: year,
      closingARR: last.closingARR,
      newARR: sum('newARR'),
      expansion: sum('expansion'),
      leakage: sum('leakage'),
      revenue: sum('revenue'),
      grossProfit: sum('grossProfit'),
      expansionCost: sum('expansionCost'),
      ebita: sum('ebita'),
      fcf: sum('fcf'),
      burn: sum('burn'),
      cashClosing: last.cashClosing,
      nrrAnnualised: last.nrrAnnualised,
      arrGrowthYoY: last.arrGrowthYoY,
      ebitaMargin: sum('revenue') > 0 ? sum('ebita') / sum('revenue') : 0
    };
  }

  function annualSummary(res) {
    var years = [], n = Math.ceil(res.horizon / 12);
    for (var y = 1; y <= n; y++) years.push(yearSlice(res, y));
    return years;
  }

  return {
    HORIZON: HORIZON,
    TAXONOMY: TAXONOMY,
    DEFAULT_ASSUMPTIONS: DEFAULT_ASSUMPTIONS,
    DEFAULT_START: DEFAULT_START,
    BAND_EDGES: BAND_EDGES,
    BAND_NAMES: BAND_NAMES,
    resolveBands: resolveBands,
    bandFor: bandFor,
    toMonthlyPersistence: toMonthlyPersistence,
    toMonthlyExpansion: toMonthlyExpansion,
    newARRPerMonth: newARRPerMonth,
    newMRRPerMonth: newMRRPerMonth,
    saturationEnabled: saturationEnabled,
    acquisitionResponse: acquisitionResponse,
    validateAssumptions: validateAssumptions,
    pendingEntry: pendingEntry,
    realiseCohort: realiseCohort,
    cacPerMRR: cacPerMRR,
    run: run,
    bridge: bridge,
    cohortSnapshot: cohortSnapshot,
    arrMix: arrMix,
    yearSlice: yearSlice,
    rateDiagnostics: rateDiagnostics,
    cacPaybackMonths: cacPaybackMonths,
    summarise: summarise,
    compare: compare,
    annualSummary: annualSummary
  };
});
